### PR TITLE
Fixed Crashing of Chat Activity

### LINKED ISSUE #37: App crashing while opening Chat Activity
App is crashing when existing chat with any user is opened.

### PR DESCRIPTION
**Pull request by riturajjain2000**
Fixes #37

### CODE REVIEW

**Review by plazzy99 — COMMENTED** [review]
Can you explain what type of file is recyclerView.java ?

**Comment by riturajjain2000** [comment]
There was a error coming with the original Recycler view , so I created a local copy of it , and it worked .

**Comment by lucifer0987** [comment]
@riturajjain2000 
-          ((ImageViewHolder) holder).time.setText(list.get(position).getTime());
+         ((TextViewHolder) holder).time.setText(list.get(position).getTime());

Here, you have changed the ImageViewHolder with TextViewHolder. Thats why you are getting the class cast Exception. Because, you are using the ViewHolder which was made for texts, with images and thats what causing the class cast Exception because they both are of different types.
And, adding this to the project will create even more errors. 
So, Make a fresh fork of the repo and then sync your code with develop branch.
If it still causes any error, you can share the screen and we will look at it.

**Comment by plazzy99** [comment]
> There was a error coming with the original Recycler view , so I created a local copy of it , and it worked .

this is not right way to do that

**Comment by riturajjain2000** [comment]
Ok so tried running the code with a fresh fork with the `develop` branch synced and found that there is a class cast exception of casting Imageview to Textview in the `master` branch only, that was causing the crash, and there is no need for a separate RecyclerView class, so I have removed it from the PR.

**Comment by lucifer0987** [comment]
@riturajjain2000 Can you please share your screen?
I want to know what's causing this issue, since None of us are getting this issue on our ends.

**Comment by riturajjain2000** [comment]
This was the error that I fixed  , 
Screenshot 2020-12-10 185858


I think this may be because of the API level difference in the devices that we are using , mine is API level 30

**Comment by riturajjain2000** [comment]
Closing as further improvements are required

**Pull request closed without merging**
